/*
 * Investabit
 * The Investabit API allows for access to all of the public facing services provided, including market data and forecasts.  ## General Overview  1. All API methods will be built to adhere to RESTful best practices as closely as possible. As such, all API calls will be made via the standard HTTP protocol using the GET/POST/PUT/DELETE request types.  2. Every request returns the status as a JSON response with the following   - success, true if it was successful   - code, the http status code (also in the response header)          200 if response is successful          400 if bad request          401 if authorization JWT is wrong or limit exceeded          404 wrong route          500 for any internal errors  - status, the status of the request, default **success**  - errors, an array of any relevant error details  3. For any requests that are not successful an error message is specified and returned as an array for the **errors** key in the JSON response.  4. All authentication uses JSON Web Tokens (JWT), which is set as the **Authorization** entry in the header, see the following for more details.     * http://jwt.io     * https://scotch.io/tutorials/the-anatomy-of-a-json-web-token
 *
 * OpenAPI spec version: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.10-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Investabit);
  }
}(this, function(expect, Investabit) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Investabit.PublicApi();
  });

  describe('(package)', function() {
    describe('PublicApi', function() {
      describe('v1PublicPriceChangeSymbolGet', function() {
        it('should call v1PublicPriceChangeSymbolGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v1PublicPriceChangeSymbolGet call and complete the assertions
          /*
          var symbol = "btc";

          instance.v1PublicPriceChangeSymbolGet(symbol, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Investabit.PublicPriceChangeResponse);
            expect(data.success).to.be.a('boolean');
            expect(data.success).to.be(false);
            expect(data.code).to.be.a('number');
            expect(data.code).to.be(0);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            expect(data.data).to.be.a(Investabit.PublicPriceChangeResponseData);
                  {
                let dataCtr = data.data.priceChange;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(Investabit.PublicPriceChangeResponseDataPriceChange);
                  expect(data.interval).to.be.a('string');
                  expect(data.interval).to.be("");
                  expect(data.changeUsd).to.be.a('number');
                  expect(data.changeUsd).to.be();
                  expect(data.changePct).to.be.a('number');
                  expect(data.changePct).to.be();
                }
              }
            {
              let dataCtr = data.errors;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Object);
                expect(data).to.be();
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1PublicPriceCurrentSymbolGet', function() {
        it('should call v1PublicPriceCurrentSymbolGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v1PublicPriceCurrentSymbolGet call and complete the assertions
          /*
          var symbol = "btc";

          instance.v1PublicPriceCurrentSymbolGet(symbol, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Investabit.PublicPriceCurrentResponse);
            expect(data.success).to.be.a('boolean');
            expect(data.success).to.be(false);
            expect(data.code).to.be.a('number');
            expect(data.code).to.be(0);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            expect(data.data).to.be.a(Investabit.PublicPriceCurrentResponseData);
                  {
                let dataCtr = data.data.current;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(Investabit.PublicPriceCurrentResponseDataCurrent);
                  expect(data.symbol).to.be.a('string');
                  expect(data.symbol).to.be("");
                  expect(data.name).to.be.a('string');
                  expect(data.name).to.be("");
                  expect(data.price).to.be.a('number');
                  expect(data.price).to.be();
                  expect(data.changeUsd).to.be.a('number');
                  expect(data.changeUsd).to.be();
                  expect(data.changePct).to.be.a('number');
                  expect(data.changePct).to.be();
                }
              }
            {
              let dataCtr = data.errors;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Object);
                expect(data).to.be();
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1PublicPriceHistorySymbolPeriodIntervalGet', function() {
        it('should call v1PublicPriceHistorySymbolPeriodIntervalGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v1PublicPriceHistorySymbolPeriodIntervalGet call and complete the assertions
          /*
          var symbol = "btc";
          var period = "30d";
          var interval = "1d";

          instance.v1PublicPriceHistorySymbolPeriodIntervalGet(symbol, period, interval, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Investabit.PublicPriceHistoryResponse);
            expect(data.success).to.be.a('boolean');
            expect(data.success).to.be(false);
            expect(data.code).to.be.a('number');
            expect(data.code).to.be(0);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            expect(data.data).to.be.a(Investabit.PublicPriceHistoryResponseData);
                  {
                let dataCtr = data.data.priceHistory;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(Investabit.PublicPriceHistoryResponseDataPriceHistory);
                  expect(data.symbol).to.be.a('string');
                  expect(data.symbol).to.be("");
                  expect(data.name).to.be.a('string');
                  expect(data.name).to.be("");
                  {
                    let dataCtr = data.history;
                    expect(dataCtr).to.be.an(Array);
                    expect(dataCtr).to.not.be.empty();
                    for (let p in dataCtr) {
                      let data = dataCtr[p];
                      expect(data).to.be.a(Investabit.PublicPriceHistoryResponseDataHistory);
                      expect(data.time).to.be.a('number');
                      expect(data.time).to.be();
                      expect(data.price).to.be.a('number');
                      expect(data.price).to.be();
                    }
                  }
                }
              }
            {
              let dataCtr = data.errors;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Object);
                expect(data).to.be();
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1PublicSymbolsGet', function() {
        it('should call v1PublicSymbolsGet successfully', function(done) {
          // TODO: uncomment v1PublicSymbolsGet call and complete the assertions
          /*

          instance.v1PublicSymbolsGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Investabit.PublicSymbolsResponse);
            expect(data.success).to.be.a('boolean');
            expect(data.success).to.be(false);
            expect(data.code).to.be.a('number');
            expect(data.code).to.be(0);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            expect(data.data).to.be.a(Investabit.PublicSymbolsResponseData);
                  {
                let dataCtr = data.data.symbols;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(Investabit.PublicSymbolsResponseDataSymbols);
                  expect(data.name).to.be.a('string');
                  expect(data.name).to.be("");
                  expect(data.symbol).to.be.a('string');
                  expect(data.symbol).to.be("");
                }
              }
            {
              let dataCtr = data.errors;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Object);
                expect(data).to.be();
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1PublicTrendSymbolGet', function() {
        it('should call v1PublicTrendSymbolGet successfully', function(done) {
          // TODO: uncomment, update parameter values for v1PublicTrendSymbolGet call and complete the assertions
          /*
          var symbol = "btc";

          instance.v1PublicTrendSymbolGet(symbol, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Investabit.PublicTrendResponse);
            expect(data.success).to.be.a('boolean');
            expect(data.success).to.be(false);
            expect(data.code).to.be.a('number');
            expect(data.code).to.be(0);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            expect(data.data).to.be.a(Investabit.PublicTrendResponseData);
                  {
                let dataCtr = data.data.trend;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(Investabit.PublicTrendResponseDataTrend);
                  expect(data.timeStart).to.be.a('number');
                  expect(data.timeStart).to.be();
                  expect(data.timeEnd).to.be.a('number');
                  expect(data.timeEnd).to.be();
                  expect(data.interval).to.be.a('string');
                  expect(data.interval).to.be("");
                  expect(data.weightedPrice).to.be.a('number');
                  expect(data.weightedPrice).to.be();
                  expect(data.changeUsd).to.be.a('number');
                  expect(data.changeUsd).to.be();
                  expect(data.changePct).to.be.a('number');
                  expect(data.changePct).to.be();
                  expect(data.confidence).to.be.a('number');
                  expect(data.confidence).to.be();
                }
              }
            {
              let dataCtr = data.errors;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Object);
                expect(data).to.be();
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('v1PublicWaitingListPost', function() {
        it('should call v1PublicWaitingListPost successfully', function(done) {
          // TODO: uncomment, update parameter values for v1PublicWaitingListPost call and complete the assertions
          /*
          var opts = {};
          opts.body = new Investabit.PublicWaitingListRequest();
          opts.body.name = "";
          opts.body.email = "";
          opts.body.service = "";
          opts.body.listId = "";

          instance.v1PublicWaitingListPost(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Investabit.DefaultResponse);
            expect(data.success).to.be.a('boolean');
            expect(data.success).to.be(false);
            expect(data.code).to.be.a('number');
            expect(data.code).to.be(0);
            expect(data.status).to.be.a('string');
            expect(data.status).to.be("");
            {
              let dataCtr = data.errors;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(Object);
                expect(data).to.be();
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
